
import { Scene } from '../types';

export const buildPromptGuideHtml = (title: string, scenes: Scene[], promptExtractor: (s: Scene) => string): string => {
    const items = scenes.map((scene, index) => ({
        id: index + 1,
        content: promptExtractor(scene),
        image: scene.imageUrl // Capture image URL for HTML embedding
    }));

    return `<!DOCTYPE html>
<html lang="ko">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>${title}</title>
    <script src="https://cdn.tailwindcss.com"></script>
    <style>
        body { background-color: #111827; color: white; font-family: 'Pretendard', sans-serif; }
        ::-webkit-scrollbar { width: 8px; }
        ::-webkit-scrollbar-track { background: #1f2937; }
        ::-webkit-scrollbar-thumb { background: #4b5563; border-radius: 4px; }
        .toast { position: fixed; top: 20px; left: 50%; transform: translateX(-50%); background: #10B981; color: white; padding: 10px 20px; border-radius: 30px; opacity: 0; transition: opacity 0.3s; pointer-events: none; z-index: 100; font-weight: bold; box-shadow: 0 10px 25px rgba(0,0,0,0.5); border: 1px solid #34D399; }
        .toast.show { opacity: 1; transform: translateX(-50%) translateY(10px); }
    </style>
    <link rel="stylesheet" as="style" crossorigin href="https://cdn.jsdelivr.net/gh/orioncactus/pretendard@v1.3.9/dist/web/static/pretendard.min.css" />
</head>
<body class="bg-gray-900 min-h-screen p-8 selection:bg-blue-500 selection:text-white">
    <div id="toast" class="toast">✅ 클립보드에 복사되었습니다!</div>

    <div class="max-w-6xl mx-auto">
        <header class="flex flex-col md:flex-row justify-between items-center mb-10 border-b border-gray-800 pb-8 gap-4">
            <div>
                <h1 class="text-4xl font-black text-transparent bg-clip-text bg-gradient-to-r from-blue-400 via-purple-400 to-pink-400 mb-2">${title}</h1>
                <p class="text-gray-400 font-medium">Total ${items.length} Scenes | AI Prompt Guide</p>
            </div>
            <button onclick="copyAll()" class="px-8 py-3 bg-blue-600 hover:bg-blue-500 text-white rounded-2xl font-bold shadow-lg shadow-blue-900/30 transition-all transform hover:scale-105 flex items-center gap-2 border border-blue-400/30">
                <span class="text-xl">📋</span>
                <span>전체 복사 (Copy All)</span>
            </button>
        </header>

        <div class="grid grid-cols-1 gap-4">
            ${items.map(item => `
            <div class="bg-gray-800 rounded-2xl border border-gray-700 p-1 flex gap-0 hover:border-blue-500/50 transition-colors shadow-lg group relative overflow-hidden">

                <!-- Scene Number -->
                <div class="flex-shrink-0 w-16 bg-gray-900/50 rounded-xl flex flex-col items-center justify-center border-r border-gray-700/50 m-1">
                    <span class="text-blue-500 font-black text-xs uppercase tracking-wider">SCENE</span>
                    <span class="text-white font-black text-2xl">#${item.id}</span>
                </div>

                <!-- Thumbnail Image (New) -->
                ${item.image ? `
                <div class="flex-shrink-0 w-32 bg-black border-r border-gray-700/50 m-1 rounded-lg overflow-hidden relative group/img">
                    <img src="${item.image}" class="w-full h-full object-cover opacity-90 group-hover:opacity-100 transition-opacity" loading="lazy" />
                </div>
                ` : ''}

                <!-- Content -->
                <div class="flex-grow min-w-0 p-4 flex items-center">
                    <p id="prompt-${item.id}" class="text-gray-300 text-sm leading-relaxed font-mono whitespace-pre-wrap select-all w-full">${item.content.replace(/</g, '&lt;').replace(/>/g, '&gt;')}</p>
                </div>

                <!-- Copy Button -->
                <div class="flex-shrink-0 flex items-center pr-2">
                    <button onclick="copySingle('prompt-${item.id}', this)" class="p-3 bg-gray-700/50 hover:bg-blue-600 text-gray-400 hover:text-white rounded-xl transition-all shadow-md active:scale-95 border border-gray-600 hover:border-blue-400" title="이 프롬프트만 복사">
                        <svg class="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M8 7v8a2 2 0 002 2h6M8 7V5a2 2 0 012-2h4.586a1 1 0 01.707.293l4.414 4.414a1 1 0 01.293.707V15a2 2 0 01-2 2h-2M8 7H6a2 2 0 00-2 2v10a2 2 0 002h8a2 2 0 002-2v-2"></path></svg>
                    </button>
                </div>
            </div>
            `).join('')}
        </div>

        <footer class="mt-12 text-center text-gray-600 text-xs font-medium">
            Generated by AI All-in-One Production
        </footer>
    </div>

    <script>
        function showToast() {
            const t = document.getElementById('toast');
            t.classList.add('show');
            setTimeout(() => t.classList.remove('show'), 2000);
        }

        function copySingle(elementId, btn) {
            const text = document.getElementById(elementId).innerText;
            navigator.clipboard.writeText(text).then(() => {
                showToast();
                const original = btn.innerHTML;
                btn.innerHTML = '<span class="text-lg">✅</span>';
                btn.classList.add('bg-green-600', 'text-white', 'border-green-400');
                btn.classList.remove('bg-gray-700/50', 'text-gray-400', 'border-gray-600');
                setTimeout(() => {
                    btn.innerHTML = original;
                    btn.classList.remove('bg-green-600', 'text-white', 'border-green-400');
                    btn.classList.add('bg-gray-700/50', 'text-gray-400', 'border-gray-600');
                }, 1500);
            });
        }

        function copyAll() {
            const prompts = [];
            ${JSON.stringify(items.map(i => i.id))}.forEach(id => {
                const text = document.getElementById('prompt-' + id).innerText;
                prompts.push('=== Scene ' + id + ' ===\\n' + text);
            });
            const allText = prompts.join('\\n\\n');
            navigator.clipboard.writeText(allText).then(() => {
                showToast();
            });
        }
    </script>
</body>
</html>`;
};
